services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: egt
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  
  sim-service:
    build: ./sim_service
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      SIM_INTERNAL_TOKEN: ${SIM_INTERNAL_TOKEN}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - miniodata:/data


volumes:
  miniodata: