spring.datasource.url=jdbc:postgresql://localhost:5432/egt
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


sim.service.url=http://localhost:8000
sim.service.token=${SIM_INTERNAL_TOKEN}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

minio.url=http://localhost:9000
minio.user=${MINIO_USER}
minio.password=${MINIO_PASSWORD}
minio.bucket=${MINIO_BUCKET}