spring.application.name=egt-api
spring.datasource.url=jdbc:postgresql://localhost:5432/egt
spring.datasource.username=egt
spring.datasource.password=egt
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
